/*****************************************************************************
 INMPIW Query
 This is part of "INMPIW" the MPI wrapper software system.

 Copyright (c) 2019, Ioannis Nompelis. All rights reserved.

 Code to query the target system's MPI implementation's constants and typdef
 sizes. This needs to be compiled with "mpicc" on the target system. It
 creates a header file (with some typedefs and other definitions) that is to
 be used by other INMPIW components to build a run-time library.
 *****************************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <mpi.h>


//
// variables to store the sizes (in bytes) of regular types
//

size_t inmpiw_mpi_datatype;
size_t inmpiw_mpi_status;
size_t inmpiw_mpi_request;
size_t inmpiw_mpi_info;
size_t inmpiw_mpi_group;
size_t inmpiw_mpi_op;
size_t inmpiw_mpi_message;
size_t inmpiw_mpi_win;
size_t inmpiw_mpi_errhandler;

//
// a presumed maximum size of preprocessor directives/macros for stringification
//

#define INMPIW_DESC_STRING_SIZE   128

//
// string variables to capture stringified preprocessor macros
//

char inmpiw_mpi_status_ignore[ INMPIW_DESC_STRING_SIZE ];
char inmpiw_mpi_statuses_ignore[ INMPIW_DESC_STRING_SIZE ];


//
// A function to provide info
//
void preamble( FILE *fp )
{

   fprintf(fp," -----------------------------------------");
   fprintf(fp,"-----------------------------\n");
   fprintf(fp,"  INMPIW Query \n");
   fprintf(fp,"  Part of the INMPIW MPI Wrapper system. ");
   fprintf(fp,"Built: %s \n", __DATE__ );
   fprintf(fp,"  Copyright (c) 2019, Ioannis Nompelis. ");
   fprintf(fp,"All rights reserved. \n");
   fprintf(fp,"  Info: <software@nobelware.com> \n");
   fprintf(fp," -----------------------------------------");
   fprintf(fp,"-----------------------------\n");

}


//
// The driver that performs queries for the OpenMPI implementation
//
int write_header_file( char filename[] )
{
   FILE *fp = stdout, *file;


   //
   // dump a header file with the sized typdefs and other definitions
   //
   file = fopen( filename, "w" );
   if( file == NULL ) {
      fprintf(fp,"Error. Could not create file \"%s\"\n",filename);
      return(1);
   }
   fprintf(fp, "Writing header file: \"%s\"\n",filename);

   fprintf(file,"#ifndef _INMPIW_DEFS_H_\n");
   fprintf(file,"#define _INMPIW_DEFS_H_\n\n");

   fprintf(file,"/*\n * File automatically generated by INMPIW-Query \n *\n");
   preamble( file );
   fprintf(file," */\n");

   fprintf(file,"\n\n");

   fprintf(fp  ,"typedef struct { char mem[%d]; } INMPIW_Datatype; \n",
              (int) inmpiw_mpi_datatype );
   fprintf(file,"typedef struct { char mem[%d]; } INMPIW_Datatype; \n",
              (int) inmpiw_mpi_datatype );

   fprintf(fp  ,"typedef struct { char mem[%d]; } INMPIW_Status; \n",
              (int) inmpiw_mpi_status );
   fprintf(file,"typedef struct { char mem[%d]; } INMPIW_Status; \n",
              (int) inmpiw_mpi_status );

   fprintf(fp  ,"typedef struct { char mem[%d]; } INMPIW_Request; \n",
              (int) inmpiw_mpi_request );
   fprintf(file,"typedef struct { char mem[%d]; } INMPIW_Request; \n",
              (int) inmpiw_mpi_request );

   fprintf(fp,  "typedef struct { char mem[%d]; } INMPIW_Info; \n",
              (int) inmpiw_mpi_info );
   fprintf(file,"typedef struct { char mem[%d]; } INMPIW_Info; \n",
              (int) inmpiw_mpi_info );

   fprintf(fp  ,"typedef struct { char mem[%d]; } INMPIW_Group; \n",
              (int) inmpiw_mpi_group );
   fprintf(file,"typedef struct { char mem[%d]; } INMPIW_Group; \n",
              (int) inmpiw_mpi_group );

   fprintf(fp  ,"typedef struct { char mem[%d]; } INMPIW_Op; \n",
              (int) inmpiw_mpi_op );
   fprintf(file,"typedef struct { char mem[%d]; } INMPIW_Op; \n",
              (int) inmpiw_mpi_op );

   fprintf(fp  ,"typedef struct { char mem[%d]; } INMPIW_Message; \n",
              (int) inmpiw_mpi_message );
   fprintf(file,"typedef struct { char mem[%d]; } INMPIW_Message; \n",
              (int) inmpiw_mpi_message );

   fprintf(fp  ,"typedef struct { char mem[%d]; } INMPIW_Win; \n",
              (int) inmpiw_mpi_win );
   fprintf(file,"typedef struct { char mem[%d]; } INMPIW_Win; \n",
              (int) inmpiw_mpi_win );

   fprintf(fp  ,"typedef struct { char mem[%d]; } INMPIW_Errhandler; \n",
              (int) inmpiw_mpi_errhandler );
   fprintf(file,"typedef struct { char mem[%d]; } INMPIW_Errhandler; \n",
              (int) inmpiw_mpi_errhandler );


   fprintf( fp  , "#define    INMPIW_STATUS_IGNORE        %s\n",
                   inmpiw_mpi_status_ignore );
   fprintf( file, "#define    INMPIW_STATUS_IGNORE        %s\n",
                   inmpiw_mpi_status_ignore );
   fprintf( fp  , "#define    INMPIW_STATUSES_IGNORE      %s\n",
                   inmpiw_mpi_statuses_ignore );
   fprintf( file, "#define    INMPIW_STATUSES_IGNORE      %s\n",
                   inmpiw_mpi_statuses_ignore );


   fprintf(file,"\n\n");
   fprintf(file,"#endif\n");

   fclose( file );

   return( EXIT_SUCCESS );
}


#ifdef _OPENMPI_
//
// The driver that performs queries for the OpenMPI implementation
//
int main( int argc, char *argv[] )
{
   FILE *fp = stdout;
   char filename[] = "inmpiw_defs.h";


   preamble( fp );

   //
   // items that occupy memory and require to have their size queried
   //
   fprintf(fp," Queried sizes of the MPI implementation typdefs :\n");

   inmpiw_mpi_datatype = sizeof( MPI_Datatype );
   printf(" - Size of MPI_Datatype is %d \n", (int) inmpiw_mpi_datatype );

   inmpiw_mpi_status = sizeof( MPI_Status );
   printf(" - Size of MPI_Status is %d \n", (int) inmpiw_mpi_status );

   inmpiw_mpi_request = sizeof( MPI_Request );;
   printf(" - Size of MPI_Request is %d \n", (int) inmpiw_mpi_request );

   inmpiw_mpi_info = sizeof( MPI_Info );;
   printf(" - Size of MPI_Info is %d \n", (int) inmpiw_mpi_info );

   inmpiw_mpi_group = sizeof( MPI_Group );;
   printf(" - Size of MPI_Group is %d \n", (int) inmpiw_mpi_group );

   inmpiw_mpi_op = sizeof( MPI_Op );;
   printf(" - Size of MPI_Op is %d \n", (int) inmpiw_mpi_op );

   inmpiw_mpi_message = sizeof( MPI_Message );;
   printf(" - Size of MPI_Message is %d \n", (int) inmpiw_mpi_message );

   inmpiw_mpi_win = sizeof( MPI_Win );;
   printf(" - Size of MPI_Win is %d \n", (int) inmpiw_mpi_win );

   inmpiw_mpi_errhandler = sizeof( MPI_Errhandler );;
   printf(" - Size of MPI_Errhandler is %d \n", (int) inmpiw_mpi_errhandler );


   //
   // items that are built using preprocessor directives and need to be
   // copied as strings
   //
// sprintf( inmpiw_mpi_status_ignore, " " #MPI_STATUS_IGNORE "\0" );
// sprintf( inmpiw_mpi_status_ignore, " " #MPI_STATUS_IGNORE );
// printf("Macro of MPI_STATUS_IGNORE is \"%s\" \n", inmpiw_mpi_status_ignore );

   // the following is a remedy
   sprintf( inmpiw_mpi_status_ignore, "(MPI_Status *) 0" );

// sprintf( inmpiw_mpi_statuses_ignore, " " #MPI_STATUSES_IGNORE "\0" );
// printf("Macro of MPI_STATUSES_IGNORE is \"%s\" \n", inmpiw_mpi_statuses_ignore );
   // the following is a remedy
   sprintf( inmpiw_mpi_statuses_ignore, "(MPI_Status *) 0" );


   //
   // create the header file
   //
   (void) write_header_file( filename );

   return( EXIT_SUCCESS );
}

#endif

